#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys, json, smtplib, ssl, base64
from PyQt5.QtWidgets import QComboBox,QApplication,QDesktopWidget,QMessageBox,QFileDialog,QWidget,QLabel,QTextEdit,QLineEdit,QPushButton,QVBoxLayout,QHBoxLayout
from PyQt5 import QtCore
from pathlib import Path
from email.message import EmailMessage

VERSION="1.0"

class EmailContainer:
    """
        Class to manage, contain and send a mail message through a SMTP server.
    """
    def __init__( self ):
        self.myMessage = EmailMessage()

    def addFrom( self, tmpFrom ):
        self.myMessage['From']=tmpFrom

    def addTo( self, tmpTo ):
        self.myMessage['To']=tmpTo

    def addCC( self, tmpCC ):
        self.myMessage['CC']=tmpCC

    def addSubject( self, tmpSubject ):
        self.myMessage['Subject']=tmpSubject

    def addMessage( self, tmpMessage ):
        self.myMessage.set_content( tmpMessage )

    def addAttachment( self, tmpFileName ):
        self.myMessage.add_attachment( open( tmpFileName, "r").read(), filename=tmpFileName )

    def sendMessage( self, tmpServerData ):
        print("Sending via "+tmpServerData['NAME']+"...")
        try:
            if tmpServerData['PORT']==587:
                tmpServer = smtplib.SMTP( tmpServerData['SERVER'], tmpServerData['PORT'] )
                tmpServer.ehlo()
                tmpServer.starttls( context=ssl.create_default_context() )
            elif tmpServerData['PORT']==465:
                tmpServer = smtplib.SMTP_SSL( tmpServerData['SERVER'], tmpServerData['PORT'] )
                tmpServer.ehlo()
            else:
                print("Error: No valid port found.")
                return False
            tmpServer.login( tmpServerData['USERNAME'], base64.b64decode( tmpServerData['PASSWD'] ).decode('utf-8') )
            tmpServer.send_message( self.myMessage )
            tmpServer.close()
        except Exception as e:
            print("Error: "+str(e))
        else:
            print("Mail successfully sent to "+self.myMessage['To'])


class MessageWindow( QWidget ):
    """
    GUI Part of the email message window.
    """
    def __init__( self, tmpRecipients ): #Class constructor
        super().__init__()
#Read configuration file
        with open( str( Path('~').expanduser() ) + '/.config/mailto/config.json', 'r') as tmpConfigFile:
            tmpConfigStore = json.load(tmpConfigFile)
#Store config within class
        self.myConfiguration = tmpConfigStore
#Create UI
        self.initUI()
#Initialize string to hold one or multiple recipients
        tmpRecipientsString = ""
#Delete first argument (the script name)
        del tmpRecipients[0]
#Initialize new mail Message
        for tmpTo in tmpRecipients:
            tmpRecipientsString += tmpTo+","
        tmpRecipientsString = tmpRecipientsString.strip(",")
        self.setWindowTitle( 'mailto: '+tmpRecipientsString )
        self.myRecipients = tmpRecipientsString

    def initUI( self ): #UI Creation
        self.setGeometry( 0, 0, 600, 600 )
        tmpCenter = QDesktopWidget().availableGeometry().center()
        tmpFrame = self.frameGeometry()
        tmpFrame.moveCenter( tmpCenter )
        self.move(tmpFrame.topLeft())
#Set default font
        #self.myEditorFont = QFont()
#Create Layouts
        self.myHorizontalLayout = QHBoxLayout()
        self.myVerticalLayout = QVBoxLayout()
#Create labels
        self.mySourceAccountLabel = QLabel("Account:", alignment=QtCore.Qt.AlignLeft)
        self.myCarboncopyLabel = QLabel("CC:", alignment=QtCore.Qt.AlignLeft)
        self.mySubjectLabel = QLabel("Subject:", alignment=QtCore.Qt.AlignLeft)
        self.myAttachmentLabel = QLabel( "Attachments: none", alignment=QtCore.Qt.AlignCenter )
#Create Dropdown
        self.mySourceAccountBox = QComboBox()
        for tmpAccount in self.myConfiguration["SMTPaccounts"]:
            self.mySourceAccountBox.addItem( tmpAccount["NAME"]+" <"+tmpAccount["SENDER"]+">" )
#Create Input Fields
        self.myCarboncopyLine = QLineEdit()
        self.mySubjectLine = QLineEdit()
#Create Message Field
        self.myTextInputField = QTextEdit()
        tmpFont = self.myTextInputField.font()
        tmpFont.setFamily("Arial")
        tmpFont.setPointSize(11)
        self.myTextInputField.setFont(tmpFont)
#Create Buttons and add them to they corresponding layout
        self.mySendButton = QPushButton("Send")
        self.mySendButton.clicked.connect( self.sendButtonClicked )
        self.mySendButton.setStyleSheet("background-color: #007fff; color: white; font-weight: bold;")
        self.myCancelButton = QPushButton("Cancel")
        self.myCancelButton.clicked.connect( self.cancelButtonClicked )
        self.myCancelButton.setStyleSheet("background-color: #e30022; color: white; ")
        self.myAttachFileButton = QPushButton("Attach")
        self.myAttachFileButton.clicked.connect( self.attachmentButtonClicked )
        self.myHorizontalLayout.addWidget( self.myCancelButton )
        self.myHorizontalLayout.addWidget( self.myAttachFileButton )
        self.myHorizontalLayout.addWidget( self.mySendButton )
#Add widgets to vertical layout
        self.myVerticalLayout.addWidget( self.mySourceAccountLabel )
        self.myVerticalLayout.addWidget( self.mySourceAccountBox )
        self.myVerticalLayout.addWidget( self.myCarboncopyLabel )
        self.myVerticalLayout.addWidget( self.myCarboncopyLine )
        self.myVerticalLayout.addWidget( self.mySubjectLabel )
        self.myVerticalLayout.addWidget( self.mySubjectLine )
        self.myVerticalLayout.addWidget( self.myTextInputField )
        self.myVerticalLayout.addWidget( self.myAttachmentLabel )
#Stack Layouts
        self.myVerticalLayout.addLayout( self.myHorizontalLayout )
#Add stack to Window
        self.setLayout( self.myVerticalLayout )
#Show all
        self.show()

    def cancelButtonClicked( self ):
        tmpMessageBox = QMessageBox( self )
        tmpMessageBox.setWindowTitle("Cancel")
        tmpMessageBox.setText("This will discard the actual message and close this window.\nAre you sure to proceed?")
        tmpMessageBox.setIcon( QMessageBox.Question )
        tmpMessageBox.setStandardButtons( QMessageBox.Yes | QMessageBox.Cancel )
        tmpResponse = tmpMessageBox.exec()
        if tmpResponse == QMessageBox.Yes:
            print("Discarding message.")
            QApplication.quit()

    def attachmentButtonClicked( self ):
        print("Attachment button clicked, but there is no functionality yet!")
        tmpFileSelector = QFileDialog()
        tmpFileSelector.setFileMode( QFileDialog.AnyFile )
        tmpFileSelector.exec_()

    def sendButtonClicked( self ):
        tmpCurrentAccount=self.myConfiguration["SMTPaccounts"][self.mySourceAccountBox.currentIndex()]
        tmpMailMessage = EmailContainer()
        tmpMailMessage.addFrom( tmpCurrentAccount['SENDER'] )
        tmpMailMessage.addTo( self.myRecipients )
        if self.myCarboncopyLine.text()!="":
            tmpMailMessage.addCC( self.myCarboncopyLine.text() )
        tmpMailMessage.addSubject( self.mySubjectLine.text() )
        tmpMailMessage.addMessage( self.myTextInputField.toPlainText() )
        tmpMailMessage.sendMessage( tmpCurrentAccount )
        self.close()


if __name__=="__main__":
    print("Launching MailTo Version "+VERSION+", written by D.Sánchez (c)2022")
    myApplication = QApplication( sys.argv )
    myWindow = MessageWindow( sys.argv )
    sys.exit( myApplication.exec_() )

# QTextbox with mime capabilities
# https://www.pythonguis.com/examples/python-rich-text-editor/
